name: myFirstWorkflow

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  MyfirstJob:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Print hello message
        run: echo "Hello World!"

      - name: List files in the repository
        run: |
          echo "The repository ${{ github.repository }} contains the following files:"
          tree
